# Generated by Django 3.2.5 on 2021-07-05 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210705_1436'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['display_name']},
        ),
    ]
