# Generated by Django 3.2.14 on 2022-11-15 10:21

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventpage',
            old_name='event_end',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='eventpage',
            old_name='event_link',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='eventpage',
            old_name='event_start',
            new_name='start',
        ),
        migrations.RemoveField(
            model_name='eventpage',
            name='ticket_link',
        ),
        migrations.AddField(
            model_name='eventpage',
            name='location',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='description',
            field=wagtail.fields.RichTextField(verbose_name='Long description'),
        ),
    ]
