# Generated by Django 3.2.4 on 2021-06-21 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_recruiterpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpage',
            name='recruiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.recruiterpage'),
        ),
    ]
