# Generated by Django 3.2.4 on 2021-06-25 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailusers', '0010_userprofile_updated_comments_notifications'),
        ('jobs', '0005_jobpage_recruiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterpage',
            name='user_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailusers.userprofile'),
        ),
        migrations.AlterField(
            model_name='recruiterpage',
            name='address_address1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='recruiterpage',
            name='address_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recruiterpage',
            name='address_postcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='recruiterpage',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='recruiterpage',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
