# Generated by Django 3.2.4 on 2021-06-28 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20210625_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiterpage',
            name='user_id',
        ),
    ]
