# Generated by Django 3.2.5 on 2021-07-05 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_remove_recruiterpage_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiterpage',
            name='address_address1',
        ),
        migrations.RemoveField(
            model_name='recruiterpage',
            name='address_address2',
        ),
        migrations.RemoveField(
            model_name='recruiterpage',
            name='address_city',
        ),
        migrations.RemoveField(
            model_name='recruiterpage',
            name='address_postcode',
        ),
        migrations.RemoveField(
            model_name='recruiterpage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='recruiterpage',
            name='email',
        ),
        migrations.RemoveField(
            model_name='recruiterpage',
            name='phone',
        ),
    ]
