# Generated by Django 3.2.5 on 2021-07-23 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0009_remove_jobpage_recruiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterpage',
            name='address1',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Address line 1'),
        ),
        migrations.AddField(
            model_name='recruiterpage',
            name='address2',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Address line 2'),
        ),
        migrations.AddField(
            model_name='recruiterpage',
            name='city',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Town / City'),
        ),
        migrations.AddField(
            model_name='recruiterpage',
            name='description',
            field=models.TextField(blank=True, help_text="A little bit about yourself (don't be spammy)", max_length=4096, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='recruiterpage',
            name='display_name',
            field=models.CharField(default='test_user', help_text='Will be shown e.g. when commenting', max_length=30, verbose_name='Display name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recruiterpage',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='recruiterpage',
            name='phone',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='recruiterpage',
            name='postal_code',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Postal Code'),
        ),
        migrations.AddField(
            model_name='recruiterpage',
            name='user_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recruiterpage',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website'),
        ),
    ]
