# Generated by Django 3.2.5 on 2021-07-23 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailusers', '0010_userprofile_updated_comments_notifications'),
        ('jobs', '0011_auto_20210723_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterpage',
            name='address1',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Address line 1'),
        ),
        migrations.AddField(
            model_name='recruiterpage',
            name='address2',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Address line 2'),
        ),
        migrations.AddField(
            model_name='recruiterpage',
            name='city',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='recruiterpage',
            name='description',
            field=models.TextField(blank=True, help_text="A little bit about yourself (don't be spammy)", max_length=4096, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='recruiterpage',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='recruiterpage',
            name='phone',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='recruiterpage',
            name='postal_code',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Postal Code'),
        ),
        migrations.AddField(
            model_name='recruiterpage',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailusers.userprofile'),
        ),
        migrations.AddField(
            model_name='recruiterpage',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website'),
        ),
    ]
