# Generated by Django 3.2.5 on 2021-07-23 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0012_auto_20210723_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiterpage',
            name='user',
        ),
        migrations.AddField(
            model_name='recruiterpage',
            name='user_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
