# Generated by Django 3.2.6 on 2021-08-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_auto_20210723_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpage',
            name='job_type',
            field=models.CharField(choices=[('permanent', 'Permanent'), ('contract', 'Contract'), ('temporary', 'Temporary'), ('freelance', 'Freelance')], default='permanent', max_length=300),
        ),
    ]
