# Generated by Django 3.2.6 on 2021-08-05 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_auto_20210805_0901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruiterpage',
            old_name='user',
            new_name='user_id',
        ),
    ]
