# Generated by Django 3.2.6 on 2021-08-05 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_rename_user_recruiterpage_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruiterpage',
            old_name='user_id',
            new_name='user',
        ),
    ]
