# Generated by Django 3.2.6 on 2021-08-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_rename_user_id_recruiterpage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpage',
            name='salary',
            field=models.CharField(default='0', max_length=1024, verbose_name='Salary / Rate'),
            preserve_default=False,
        ),
    ]
