# Generated by Django 3.2.6 on 2021-09-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0019_jobpage_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpage',
            name='short_description',
            field=models.CharField(default='Stuff', help_text='Appears in list views and as a subheading on the job page itself.', max_length=1024),
            preserve_default=False,
        ),
    ]
