# Generated by Django 3.2.6 on 2021-09-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0021_auto_20210902_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpage',
            name='short_description',
            field=models.CharField(help_text='A brief description of the job, One or two sentences at most. Appears in list views and as a subheading on the job page itself.', max_length=500),
        ),
    ]
