# Generated by Django 3.2.6 on 2021-09-03 08:31

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0022_alter_jobpage_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpage',
            name='description',
            field=wagtail.fields.RichTextField(verbose_name='Long description'),
        ),
        migrations.AlterField(
            model_name='jobpage',
            name='short_description',
            field=models.CharField(help_text='A brief description of the job, One or two sentences at most.', max_length=500),
        ),
    ]
