# Generated by Django 3.2.9 on 2021-12-20 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0023_auto_20210903_0831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobindexpage',
            name='search_image',
        ),
        migrations.RemoveField(
            model_name='jobpage',
            name='search_image',
        ),
        migrations.RemoveField(
            model_name='recruiterpage',
            name='search_image',
        ),
    ]
