# Generated by Django 3.1.12 on 2021-06-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210306_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediasettings',
            name='twitter',
            field=models.CharField(blank=True, help_text='Twitter Username', max_length=100),
        ),
    ]
