# Generated by Django 3.2.9 on 2021-12-20 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_socialmediasettings_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicpage',
            name='search_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='search_image',
        ),
    ]
