# Generated by Django 3.2.12 on 2022-04-19 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_modelcategory_modeltag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelcategory',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
